### ISSUE TITLE
Debug issues [dev branch]

### ISSUE THREAD

**Issue by rohan-tworks** [tworkshyd/DisplayBoard-MCU2#8]
Flashing code from dev branch casuses the following:
1. Motor movement is slow
2. Microcontroller resetting with the following error
![Screenshot](https://user-images.githubusercontent.com/66057853/85137485-f082df00-b25e-11ea-93fe-e4dd1c6d2679.jpeg)

## Steps to reproduce
- Flash the dev firmware on the board
- Observe

**Comment by ritesh007garg** [comment]
The slow movement of the rotor is due to heavy debug logging from serial port. To disable logging please change the following macro
#define VENT_DEBUG_LEVEL        VENT_DEBUG_LEVEL_NONE

**Comment by rohan-tworks** [comment]
Hi, @ritesh007garg  we tired with changing to debug level to none, the motor is not moving when we start the machine.

We have reset both the boards, but still, the motor doesn't move
We have even tried resetting both the boards, still no avail.

**Comment by rohan-tworks** [comment]
Hi, 

So we tried all levels of debugging, 

The machines work at NONE, ERR, INFO but not at HIGH

Currently, P3b-dev is set to INFO and we are capturing logs on a desktop for both the boards.

**Comment by anand-tworks** [comment]
Using INFO level. Which should be ok for now.
